sonar.projectKey=ncovachAJS_conciertos_backend
sonar.projectName=Conciertos Backend
sonar.projectVersion=1.0
sonar.organization=ncovachajs-1

# Fuentes
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Exclusiones de análisis
sonar.exclusions=\
  src/main.ts,\
  src/**/*.module.ts,\
  src/prisma/**,\
  dist/**,\
  node_modules/**,\
  coverage/**

# Cobertura (generada por jest --coverage)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusiones de cobertura
sonar.coverage.exclusions=\
  src/main.ts,\
  src/**/*.module.ts,\
  src/**/*.dto.ts,\
  src/**/*.entity.ts,\
  src/prisma/**

# Encoding
sonar.sourceEncoding=UTF-8
